apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selfsigned-app
    app.kubernetes.io/part-of: selfsigned
  name: selfsigned-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfsigned-app
  template:
    metadata:
      labels:
        app: selfsigned-app
        app.kubernetes.io/part-of: selfsigned
    spec:
      containers:
      - image: selfsigned:0.0.1-SNAPSHOT
        name: selfsigned-app
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: selfsigned-app
  labels:
    app.kubernetes.io/part-of: selfsigned
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: selfsigned-app
